In [83]:
import numpy as np
import pandas as pd

In [84]:
df = pd.read_csv(r"e:\DataSets\Teen_Mental_Health_Dataset.csv",encoding="Latin")

In [85]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [86]:
df['depression_label'].value_counts()

depression_label
0    1169
1      31
Name: count, dtype: int64

In [87]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [89]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [90]:
df['gender'].dtype  # str = object   !! remember

dtype('O')

In [91]:
X_cat =[]
for col in df.columns:
    if df[col].dtype == 'object':
        X_cat.append(col)

X_cat

['gender', 'platform_usage', 'social_interaction_level']

In [92]:
from sklearn.preprocessing import OneHotEncoder

In [93]:
oe = OneHotEncoder(sparse_output=False)
X_encoded = oe.fit_transform(df[X_cat])
X_encoded

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(1200, 8))

In [94]:
X_encoded = pd.DataFrame(X_encoded , columns=oe.get_feature_names_out(X_cat))

In [95]:
X_encoded

,gender_female,gender_male,platform_usage_Both,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_high,social_interaction_level_low,social_interaction_level_medium
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...
1195,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1196,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1197,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1198,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1199,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [96]:
df=df.drop(columns=X_cat)

In [97]:
df = pd.concat([df,X_encoded],axis = 1)

In [98]:
df.head()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_female,gender_male,platform_usage_Both,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_high,social_interaction_level_low,social_interaction_level_medium
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [99]:
df.shape

(1200, 18)

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
X = df.drop(columns=['depression_label'])
y=df['depression_label']

In [102]:
X.shape

(1200, 17)

In [103]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1195    0
1196    0
1197    0
1198    0
1199    0
Name: depression_label, Length: 1200, dtype: int64

In [104]:
X_train , X_test , y_train , y_test =train_test_split(X , y ,test_size=0.2 , random_state=20)

In [105]:
X_train.shape

(960, 17)

In [106]:
X_test.shape

(240, 17)

In [107]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [108]:
X_train

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,gender_female,gender_male,platform_usage_Both,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_high,social_interaction_level_low,social_interaction_level_medium
1083,17,6.6,5.3,1.1,3.50,1.7,1,10,7,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
909,19,7.4,8.3,1.4,3.64,0.4,6,9,6,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
308,14,7.8,4.3,2.6,3.33,2.0,3,7,3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
237,19,1.2,5.0,1.5,2.09,0.6,5,2,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
404,13,8.0,6.9,2.5,2.45,1.7,10,1,3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186,18,1.6,5.4,2.0,3.20,1.8,8,8,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
393,13,4.0,4.2,0.5,2.46,0.6,2,9,9,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
924,17,1.7,7.0,0.8,3.39,0.9,7,7,10,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
271,16,1.5,6.7,0.5,2.78,1.2,1,9,6,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
474,15,5.2,5.6,1.1,2.88,0.1,4,8,7,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0

In [109]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
Accuracy = accuracy_score(y_test,y_pred)
print("the Accuracy is : ", Accuracy)

the Accuracy is :  0.975

In [ ]:
svm = SVC(kernel='poly',degree=2) # polly because data is not continuous 
svm.fit(X_train,y_train)
y_pred = svm.predict(X_test)
Accuracy = accuracy_score(y_test,y_pred)
Accuracy

0.9625

In [111]:
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_val_score

with cross val score

In [112]:
estimators = [('lr',LogisticRegression()),('svm',SVC(probability=True)),('knn',KNeighborsClassifier())]
ensembel_model = VotingClassifier(estimators=estimators , voting='soft')
accuracy = cross_val_score(ensembel_model , X , y , cv = 10 , scoring="accuracy")
mean_accuracy = np.round(accuracy.mean(),2)
mean_accuracy

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

np.float64(0.98)

without cross val score

In [113]:
estimators = [('lr',LogisticRegression()),('svm',SVC()),('knn',KNeighborsClassifier())]
ensembel_model = VotingClassifier(estimators=estimators , voting='hard')
ensembel_model.fit(X_train,y_train)
y_pred = ensembel_model.predict(X_test)
ans=accuracy_score(y_test,y_pred)
ans

0.9708333333333333